services:
  test:
    image: test:t1
    container_name : "con"
    ports: 
      - "5000:3030"
    volumes: 
      - "/app/node_modules"
    

# docker-compose up --build -d
# docker stop con

# Только остановить контейнеры:
#  docker-compose down

# Остановить контейнеры с удаление данных (в volumes):
# docker-compose down --volumes
